package com.konasl.common.cqrs;

/**
 * Marker interface for all commands in the system.
 * Commands represent the intent to change system state.
 * 
 * CQRS PATTERN:
 * - Commands are write operations
 * - Commands do NOT return data (use queries for reads)
 * - Commands must be validated before execution
 * - Commands should be immutable
 * 
 * DDD PATTERN:
 * - Commands express business intent
 * - Commands are named with imperative verbs (CreateOrder, CancelOrder)
 * - Commands belong to a specific bounded context
 */
public interface Command {
    /**
     * Returns a unique identifier for command tracking and idempotency.
     * This ID should be generated by the client or command bus.
     */
    String getCommandId();
}
