package com.konasl.common.cqrs;

/**
 * Marker interface for all queries in the system.
 * Queries represent the intent to read system state.
 * 
 * CQRS PATTERN:
 * - Queries are read operations
 * - Queries do NOT modify state
 * - Queries can bypass domain model and read directly from read
 * models/projections
 * - Queries should be immutable
 * 
 * DDD PATTERN:
 * - Queries express information needs
 * - Queries are named with questions (GetOrderById, FindActiveCustomers)
 * - Queries can span multiple bounded contexts (denormalized views)
 */
public interface Query<R> {
    /**
     * Returns a unique identifier for query tracking and caching.
     * This ID should be generated by the client or query bus.
     */
    String getQueryId();
}
