dependencies {
    implementation project(':shared:common')
    implementation('org.springframework.boot:spring-boot-starter-web') {
        exclude group: 'org.springframework.boot', module: 'spring-boot-starter-tomcat'
    }
    implementation 'org.springframework.boot:spring-boot-starter-undertow'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
}

bootJar {
    enabled = true
    archiveFileName = 'perf-test.jar'
}

jar {
    enabled = false
}
